#!/usr/bin/expect

set timeout -1

if { $argc != 4 } {
    puts "Usage $argv0 host user pass command"
    exit 1
}

set host [lindex $argv 0]
set user [lindex $argv 1]
set pass [lindex $argv 2]
set command [lindex $argv 3]

spawn ssh -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no -oCheckHostIP=no $user@$host -p 8101
expect *assword:

send "$pass\r"
expect *>

send "$command\r"
expect *>

send "\r"
expect eof
